# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
    goarch:
      # - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath
      - -buildvcs=false

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
dockers:
  - goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=TARGETOS=linux"
      - "--build-arg=TARGETARCH=amd64"
    dockerfile: Dockerfile
    image_templates:
      - github.com/tryy3/k8-proxy:v{{ .Version }}-amd64
  - goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--build-arg=TARGETOS=linux"
      - "--build-arg=TARGETARCH=arm64"
    dockerfile: Dockerfile
    image_templates:
      - github.com/tryy3/k8-proxy:v{{ .Version }}-arm64v8
docker_manifests:
  - name_template: github.com/tryy3/k8-proxy:v{{ .Version }}
    image_templates:
      - github.com/tryy3/k8-proxy:v{{ .Version }}-amd64
      - github.com/tryy3/k8-proxy:v{{ .Version }}-arm64v8
  - name_template: github.com/tryy3/k8-proxy:latest
    image_templates:
      - github.com/tryy3/k8-proxy:v{{ .Version }}-amd64
      - github.com/tryy3/k8-proxy:v{{ .Version }}-arm64v8